sudo: required

language: none

services:
  - docker

before_install:
  - docker build -t nav2:latest --build-arg PULLREQ=$TRAVIS_PULL_REQUEST .

script:
  - docker run nav2:latest /bin/bash -c echo "Testing"
